# *******************************************************************************************
# *******************************************************************************************
#
#      Name :      copygen.py
#      Purpose :   Generate register->register copiers
#      Date :      21st March 2026
#      Author :    Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

def generate(rs,rt,name):    
    global genidx
    print(";; Copy register {0} to register {1}\n".format(rs.upper(),rt.upper()))
    print("\t.bytecode \"{1}\"\nGenCopy{0}:".format(genidx,name))
    genidx += 1
    print("\tlda\t{0}Register".format(rs))
    print("\tsta\t{0}Register".format(rt))
    print("\tlda\t{0}Register+1".format(rs))
    print("\tsta\t{0}Register+1".format(rt))
    print("\t.donext\n")
genidx = 0

print(";;\n;;\tThis file is automatically generated.\n;;")

print("\t.section code")

registers = [ "a","b","c" ]
for rs in registers:
    for rt in registers:
        if rs != rt:
            generate(rs,rt,rs+">"+rt)

print("\t.endsection")            


