# *******************************************************************************************
# *******************************************************************************************
#
#      Name :      incdecgen.py
#      Purpose :   Generate register increment;decrement
#      Date :      21st March 2026
#      Author :    Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************


def generate(rs,n,name):    
    global genidx
    print(";; Add {1} to {0} register\n".format(rs.upper(),n))
    print("\t.bytecode \"{1}\"\nGenIncDec{0}:".format(genidx,name))
    genidx += 1
    for i in range(0,abs(n)):
        print("\t.{0}word {1}Register".format("inc" if n > 0 else "dec",rs))
    print("\t.donext\n")
genidx = 0

print(";;\n;;\tThis file is automatically generated.\n;;")

print("\t.section code")

registers = [ "a","b","c" ]
shift = { "++":1,"--":-1 } #,"+++":+2,"---":-2 }
for rs in registers:
    for name,offset in shift.items():
        if offset != 0:
            generate(rs,offset,rs+name)

print("\t.endsection")            
