# *******************************************************************************************
# *******************************************************************************************
#
#      Name :      shiftgen.py
#      Purpose :   Generate A shifts
#      Date :      21st March 2026
#      Author :    Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

def generate(count):    
    global genidx
    print(";; Shift register A {0} {1}\n".format("left" if count > 0 else "right",abs(count)))
    print("\t.bytecode \"{1}{2}\"\nGenShift{0}:".format(genidx,1 << abs(count),"*" if count > 0 else "/"))
    genidx += 1
    for i in range(0,abs(count)):
        if count < 0:
            print("\tlsr aRegister+1")
            print("\tror aRegister")
        else:
            print("\tasl aRegister")
            print("\tror aRegister+1")
    print("\t.donext\n")
genidx = 0

print(";;\n;;\tThis file is automatically generated.\n;;")

print("\t.section code")

for i in range(1,5):
    generate(i)
    generate(-i)
            
print("\t.endsection")            
