# *******************************************************************************************
# *******************************************************************************************
#
#      Name :      stackgen.py
#      Purpose :   Generate register<->stack transfers
#      Date :      21st March 2026
#      Author :    Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

def generate(isPush,registers,name):    
    global genidx
    rs = [x for x in registers.upper()]
    rs.sort()
    rs = ",".join(rs)
    print(";; {0} registers {1} {2} the stack\n".format("Push" if isPush else "Pop",rs,"on" if isPush else "off"))
    print("\t.bytecode \"{1}\"\nGenStack{0}:".format(genidx,name))
    genidx += 1
    for r in registers:
        if isPush:
            print("\tlda\t{0}Register".format(r))
            print("\tpha")
            print("\tlda\t{0}Register+1".format(r))
            print("\tpha")
        else:
            print("\tpla")
            print("\tsta\t{0}Register+1".format(r))
            print("\tpla")
            print("\tsta\t{0}Register".format(r))
    print("\t.donext\n")

genidx = 0

def generatePush(registers,name = None):    
    name = registers+">" if name is None else name
    generate(True,registers,name)

def generatePop(registers,name = None):
    name = ">"+registers if name is None else name
    registers = registers[::-1]
    generate(False,registers,name)


def generatePair(registers):
    generatePush(registers)
    generatePop(registers)

print(";;\n;;\tThis file is automatically generated.\n;;")

print("\t.section code")

generatePush("abc","[")
generatePop("abc","]")
generatePush("bc","(")
generatePop("bc",")")

generatePush("a","push")

generatePair("a")
generatePair("b")
generatePair("c")

generatePair("ab")
generatePair("bc")

generatePair("abc")

print("\t.endsection")            
