# *******************************************************************************************
# *******************************************************************************************
#
#      Name :      build.py
#      Purpose :   Build class and __main builder
#      Date :      21st March 2026
#      Author :    Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import sys,os,re

# *******************************************************************************************
#
#                           Abstract processing class
#
# *******************************************************************************************

class AbstractBuilder(object):
    def __init__(self):
        self.workDirectory = sys.argv[1]
        self.includeFiles = []
        self.assemblerFiles = []
    #
    #       Generate the code
    #
    def run(self):
        self.header()
        for s in sys.argv[2:]:
            if s.startswith("-"):
                self.handleOptions(opt[0],opt[1:])
            else:
                self.scanDirectory(self.workDirectory+os.sep+s)

        for f in self.includeFiles:
            self.processInclude(f)
        for f in self.assemblerFiles:
            self.processAssembler(f)
        self.footer()
    #
    #       Output header
    #
    def header(self):
        print("{0}\n{0}\tThis file is automatically generated\n{0}".format(self.getComment()))
    #
    #       Output footer
    #
    def footer(self):
        pass
    #
    #       Scan directory for asm/inc files
    #
    def scanDirectory(self,rootDir):
        assert os.path.isdir(rootDir),"Cannot find "+rootDir
        assemblerFiles = []
        includeFiles = []
        for root,dirs,files in os.walk(rootDir):
            for f in files:
                if f.endswith(".asm"):
                    assemblerFiles.append(root+os.sep+f)
                if f.endswith(".inc"):
                    includeFiles.append(root+os.sep+f)
        assemblerFiles.sort(key = lambda f:f.split(os.sep)[-1])
        includeFiles.sort(key = lambda f:f.split(os.sep)[-1])        
        self.includeFiles += includeFiles
        self.assemblerFiles += assemblerFiles
    #
    #       Handle options
    #
    def handleOptions(self,opt,param):
        assert False
    #
    #       Get comment character(s)
    #
    def getComment(self):
        return ";"
    #
    #       Specific file processing
    #
    def processInclude(self,f):
        pass
    def processAssembler(self,f):
        pass

# *******************************************************************************************
#
#                               Main program builder class
#
# *******************************************************************************************

class MainBuilder(AbstractBuilder):
    def processInclude(self,f):
        print("\t.include \"{0}\"".format(f))
    def processAssembler(self,f):
        print("\t.include \"{0}\"".format(f))

if __name__ == "__main__":
    MainBuilder().run()

